"""T-005: Alembic migration lifecycle and drift check.

Requires a reachable Postgres. Gated behind RUN_MIGRATION_TESTS=1 so a plain
`pytest` (unit-only) run stays fast and needs no database. CI sets the flag and
provides a Postgres service.
"""
from __future__ import annotations

import os
from pathlib import Path

import pytest

pytestmark = pytest.mark.skipif(
    os.getenv("RUN_MIGRATION_TESTS") != "1",
    reason="set RUN_MIGRATION_TESTS=1 (and DATABASE_URL) to run migration tests",
)

BACKEND = Path(__file__).resolve().parents[1]


@pytest.fixture(scope="module", autouse=True)
def _clean_schema():
    """Start the migration tests from a truly empty schema.

    The DB-backed functional tests build their schema with ``create_all`` and
    leave tables behind with no ``alembic_version`` stamp. Without this reset,
    the migration test's initial ``downgrade base`` is a no-op and the following
    ``upgrade head`` collides with those leftover tables (DuplicateTable). This
    ran green locally only because a developer DB happened to be stamped; on a
    fresh CI database it would fail. Resetting makes the module state-independent.
    """
    import asyncio

    from sqlalchemy.ext.asyncio import create_async_engine
    from sqlalchemy.pool import NullPool

    url = os.getenv("DATABASE_URL")
    if not url or "@db:" in url:
        yield
        return

    async def _reset() -> None:
        engine = create_async_engine(url, poolclass=NullPool)
        try:
            async with engine.begin() as conn:
                await conn.exec_driver_sql("DROP SCHEMA public CASCADE")
                await conn.exec_driver_sql("CREATE SCHEMA public")
        finally:
            await engine.dispose()

    asyncio.run(_reset())
    yield


def _config():
    from alembic.config import Config

    cfg = Config(str(BACKEND / "alembic.ini"))
    cfg.set_main_option("script_location", str(BACKEND / "alembic"))
    return cfg


def test_upgrade_head_has_no_drift() -> None:
    """Upgrading to head then autogenerate-checking yields no pending changes.

    Guards against models and migrations diverging (INF-01).
    """
    from alembic import command

    cfg = _config()
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")
    command.check(cfg)  # raises AutogenerateDiffsDetected if models != schema


def test_downgrade_then_upgrade_roundtrips() -> None:
    from alembic import command

    cfg = _config()
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")
