"""T-005: Alembic migration lifecycle and drift check.

Requires a reachable Postgres. Gated behind RUN_MIGRATION_TESTS=1 so a plain
`pytest` (unit-only) run stays fast and needs no database. CI sets the flag and
provides a Postgres service.
"""
from __future__ import annotations

import os
from pathlib import Path

import pytest

pytestmark = pytest.mark.skipif(
    os.getenv("RUN_MIGRATION_TESTS") != "1",
    reason="set RUN_MIGRATION_TESTS=1 (and DATABASE_URL) to run migration tests",
)

BACKEND = Path(__file__).resolve().parents[1]


def _config():
    from alembic.config import Config

    cfg = Config(str(BACKEND / "alembic.ini"))
    cfg.set_main_option("script_location", str(BACKEND / "alembic"))
    return cfg


def test_upgrade_head_has_no_drift() -> None:
    """Upgrading to head then autogenerate-checking yields no pending changes.

    Guards against models and migrations diverging (INF-01).
    """
    from alembic import command

    cfg = _config()
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")
    command.check(cfg)  # raises AutogenerateDiffsDetected if models != schema


def test_downgrade_then_upgrade_roundtrips() -> None:
    from alembic import command

    cfg = _config()
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")
