"""merchants + transaction.merchant_id (T-061)

Revision ID: 1fc1ca2ac756
Revises: 563b5843825a
Create Date: 2026-08-08 13:32:50.605379

Adds the household-scoped `merchants` (normalized payee) table and an optional
`transactions.merchant_id` FK. Additive and reversible.
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1fc1ca2ac756'
down_revision: str | Sequence[str] | None = '563b5843825a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('raw_pattern', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'canonical_name', name='uq_merchants_scope_name')
    )
    op.create_index('ix_merchants_household', 'merchants', ['household_id'], unique=False)
    op.add_column('transactions', sa.Column('merchant_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_transactions_merchant_id', 'transactions', 'merchants', ['merchant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_merchant_id', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'merchant_id')
    op.drop_index('ix_merchants_household', table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
