"""transactions.edited_at for rollback safety (T-075)

Revision ID: 7c18f24b0a9e
Revises: e943450fca88
Create Date: 2026-08-15 12:54:37.449039

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c18f24b0a9e'
down_revision: str | Sequence[str] | None = 'e943450fca88'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'edited_at')
    # ### end Alembic commands ###
