"""institutions + account.institution_id (T-060)

Revision ID: a7ef2f838961
Revises: 63e60044efef
Create Date: 2026-08-08 12:58:23.851620

Adds the R1 `institutions` label table and an optional `accounts.institution_id`
FK. Additive and reversible; existing accounts keep institution_id NULL.
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a7ef2f838961'
down_revision: str | Sequence[str] | None = '63e60044efef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_FK_ACCT_INST = "fk_accounts_institution_id"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=True),
    sa.Column('logo_ref', sa.String(length=200), nullable=True),
    sa.Column('aggregator_institution_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'name', name='uq_institutions_scope_name'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_institutions_household', 'institutions', ['household_id'], unique=False)
    op.add_column('accounts', sa.Column('institution_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        _FK_ACCT_INST, 'accounts', 'institutions', ['institution_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(_FK_ACCT_INST, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'institution_id')
    op.drop_index('ix_institutions_household', table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
