"""import provenance + imported_record category (T-074)

Revision ID: e943450fca88
Revises: ef21264a17d6
Adds transaction import provenance (import_batch_id/imported_record_id) and
imported_records.category_id for the review->commit flow. Additive, reversible.

Create Date: 2026-08-15 12:46:49.425457

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e943450fca88'
down_revision: str | Sequence[str] | None = 'ef21264a17d6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imported_records', sa.Column('category_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_imported_records_category_id', 'imported_records', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.add_column('transactions', sa.Column('import_batch_id', sa.BigInteger(), nullable=True))
    op.add_column('transactions', sa.Column('imported_record_id', sa.BigInteger(), nullable=True))
    op.create_index('ix_transactions_import_batch', 'transactions', ['import_batch_id'], unique=False, postgresql_where=sa.text('import_batch_id IS NOT NULL'))
    op.create_foreign_key('fk_transactions_imported_record_id', 'transactions', 'imported_records', ['imported_record_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_transactions_import_batch_id', 'transactions', 'import_batches', ['import_batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_import_batch_id', 'transactions', type_='foreignkey')
    op.drop_constraint('fk_transactions_imported_record_id', 'transactions', type_='foreignkey')
    op.drop_index('ix_transactions_import_batch', table_name='transactions', postgresql_where=sa.text('import_batch_id IS NOT NULL'))
    op.drop_column('transactions', 'imported_record_id')
    op.drop_column('transactions', 'import_batch_id')
    op.drop_constraint('fk_imported_records_category_id', 'imported_records', type_='foreignkey')
    op.drop_column('imported_records', 'category_id')
    # ### end Alembic commands ###
