"""ingestion tables: documents, column_mappings, import_batches, imported_records (T-070)

Revision ID: ef21264a17d6
Revises: 1fc1ca2ac756
Create Date: 2026-08-15 07:32:15.478565

Creates the CSV import pipeline tables (stage -> validate -> dedup -> review ->
commit). Additive and reversible.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ef21264a17d6'
down_revision: str | Sequence[str] | None = '1fc1ca2ac756'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('csv', 'ofx', 'pdf')", name='ck_documents_kind'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_documents_household', 'documents', ['household_id'], unique=False)
    op.create_table('column_mappings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('institution_id', sa.BigInteger(), nullable=True),
    sa.Column('public_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'name', name='uq_column_mappings_scope_name'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_column_mappings_household', 'column_mappings', ['household_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('public_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=12), server_default='csv', nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_document_id', sa.BigInteger(), nullable=True),
    sa.Column('file_checksum', sa.String(length=64), nullable=False),
    sa.Column('column_mapping_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=12), server_default='staged', nullable=False),
    sa.Column('row_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('new_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dup_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('staged', 'committing', 'committed', 'rolled_back', 'failed')", name='ck_import_batches_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['column_mapping_id'], ['column_mappings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_import_batches_household', 'import_batches', ['household_id'], unique=False)
    op.create_index('ix_import_batches_status', 'import_batches', ['household_id', 'status'], unique=False)
    op.create_index('uq_import_batches_active_checksum', 'import_batches', ['household_id', 'file_checksum'], unique=True, postgresql_where="status IN ('staged', 'committing', 'committed')")
    op.create_table('imported_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('import_batch_id', sa.BigInteger(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parsed_amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('parsed_date', sa.Date(), nullable=True),
    sa.Column('parsed_currency', sa.String(length=3), nullable=True),
    sa.Column('parsed_description', sa.Text(), nullable=True),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dedup_verdict', sa.String(length=10), nullable=True),
    sa.Column('user_decision', sa.String(length=8), server_default='pending', nullable=False),
    sa.Column('committed_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dedup_verdict IS NULL OR dedup_verdict IN ('new', 'duplicate', 'near_dup')", name='ck_imported_records_verdict'),
    sa.CheckConstraint("user_decision IN ('pending', 'accept', 'skip', 'merge')", name='ck_imported_records_decision'),
    sa.ForeignKeyConstraint(['committed_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_imported_records_batch_row', 'imported_records', ['import_batch_id', 'row_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_imported_records_batch_row', table_name='imported_records')
    op.drop_table('imported_records')
    op.drop_index('uq_import_batches_active_checksum', table_name='import_batches', postgresql_where="status IN ('staged', 'committing', 'committed')")
    op.drop_index('ix_import_batches_status', table_name='import_batches')
    op.drop_index('ix_import_batches_household', table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index('ix_column_mappings_household', table_name='column_mappings')
    op.drop_table('column_mappings')
    op.drop_index('ix_documents_household', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
